### ISSUE TITLE
Could you add the HTML files to run the game from there?

### ISSUE THREAD

**Issue by HedgyhogGuy** [ZixiaChen/Eaglercraft-1.12#1]
It's just a lot easier to play the game that way and you can't block files, so its a lot more probable and useful. Please hear me out I can't play this because there's no HTML file and rawgit is blocked.

**Comment by 36479756** [comment]
beta 1.3 beta 1.7.3 alpha 1.2.7 release 1.5.2 and relese 1.8 have offline downloads so possibly

**Comment by catfoolyou** [comment]
He stole the source of my 1.12 client. This is FAKE AND SKIDDED, as well as outdated asf

**Comment by ZixiaChen** [comment]
@catfoolyou I am sorry.
Also I cloned this off https://git.zelz.net because people dont know the link to the 1.12 so I cloned it and people in GitHub can find it

**Comment by catfoolyou** [comment]
Take this down. Its outdated and skidded, and skids like ravetek are stealing it
